# Generated by Django 5.2 on 2025-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponible',
            name='fecha_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='horariodisponible',
            unique_together={('profesor', 'fecha_hora_inicio')},
        ),
    ]
