# Generated by Django 5.2 on 2025-05-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_horariodisponible_fecha_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
    ]
