# Generated by Django 5.2 on 2025-05-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_profesor_usuario'),
        ('practicas', '0004_alter_salidadisponible_profesor'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponible',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='horariodisponible',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='horariodisponible',
            constraint=models.UniqueConstraint(fields=('profesor', 'fecha_hora_inicio'), name='unique_horario_por_profesor'),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
