# Generated by Django 5.2 on 2025-05-08 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_alter_horariodisponible_fecha_hora_inicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='SalidaDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sesion', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('B', 'Mixta')], max_length=1)),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=3)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='citas.profesor')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='practicas.zona')),
            ],
            options={
                'verbose_name': 'Salida Disponible',
                'verbose_name_plural': 'Salidas Disponibles',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('sesion_preferida', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('B', 'Mixta')], max_length=1)),
                ('fecha_teorico', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('S', 'Solicitado'), ('I', 'Invitado'), ('C', 'Confirmado'), ('R', 'Rechazado'), ('E', 'Espera'), ('A', 'Asistido'), ('N', 'No Asistido')], default='S', max_length=1)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='practicas.zona')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('S', 'Solicitado'), ('I', 'Invitado'), ('C', 'Confirmado'), ('R', 'Rechazado'), ('E', 'Espera'), ('A', 'Asistido'), ('N', 'No Asistido')], default='S', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='practicas.salidadisponible')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['created_at'],
                'unique_together': {('alumno', 'salida')},
            },
        ),
        migrations.AddConstraint(
            model_name='salidadisponible',
            constraint=models.UniqueConstraint(fields=('profesor', 'fecha', 'sesion'), name='unique_salida_profesor'),
        ),
    ]
