# Generated by Django 5.2 on 2025-05-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveSmallIntegerField(help_text='Orden de la fase dentro del permiso')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='ExamenIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='practicas.solicitud')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas.fase')),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Examen',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fase_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='practicas.fase'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', related_query_name='solicitud', to='practicas.permiso'),
        ),
        migrations.CreateModel(
            name='PermisoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.fase')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisofases', related_query_name='permisofase', to='practicas.permiso')),
            ],
            options={
                'verbose_name': 'Permiso - Fase',
                'verbose_name_plural': 'Permisos - Fases',
                'ordering': ['orden'],
                'unique_together': {('permiso', 'fase')},
            },
        ),
        migrations.AddField(
            model_name='permiso',
            name='fases',
            field=models.ManyToManyField(related_name='permisos', through='practicas.PermisoFase', to='practicas.fase'),
        ),
    ]
