# Generated by Django 5.2 on 2025-05-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_fase_permiso_examenintento_solicitud_fase_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', related_query_name='solicitud', to='practicas.permiso'),
        ),
    ]
