# Generated by Django 5.2 on 2025-05-17 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0004_alter_salidadisponible_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='telefono',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
